### PR TITLE
Add possibility to configure colors

### PR DESCRIPTION
**Pull request by vgaidarji**

### CODE REVIEW

**Comment by vgaidarji** [comment]
@michaelneale If everything is fine, I merge this and prepare a release of the plugin

**Comment by michaelneale** [comment]
@vgaidarji yes. I put my pwd in settings.xml as per instructions (encrypted) and it works fine. Worth a try.

**Comment by michaelneale** [comment]
obviously you will need to merge this to master first before running 

mvn release:prepare release:perform

**Comment by vgaidarji** [comment]
@michaelneale ok, thanks. I wanted you to check the PR before merge.

**Pull request merged**
